// src/constants/morocco.cities.ts
export const MOROCCO_CITIES: readonly string[] = [
  "Agadir",
  "Al Hoceïma",
  "Beni Mellal",
  "Berkane",
  "Berrechid",
  "Bouznika",
  "Casablanca",
  "Chefchaouen",
  "Dakhla",
  "El Jadida",
  "Errachidia",
  "Essaouira",
  "Fès",
  "Fnideq",
  "Guelmim",
  "Ifrane",
  "Kénitra",
  "Khémisset",
  "Khouribga",
  "Ksar El Kébir",
  "Larache",
  "Laâyoune",
  "Marrakech",
  "Martil",
  "Meknès",
  "Mohammédia",
  "Nador",
  "Ouarzazate",
  "Oujda",
  "Rabat",
  "Safi",
  "Salé",
  "Sefrou",
  "Settat",
  "Sidi Bennour",
  "Sidi Slimane",
  "Skhirat",
  "Tanger",
  "Taounate",
  "Taroudant",
  "Taza",
  "Témara",
  "Tétouan",
];
